# AFAICT, switching to a container-based build would require hard-coding
# the current kernel version in the linux-headers-* package name.  Bleh.
sudo: required

language: c

compiler: gcc

before_install:
  - sudo apt-get -qq -y update
  - sudo apt-get -qq -y install linux-headers-$(uname -r)

script: make
